### ISSUE TITLE
Use same primary-color as antd's latest version

### ISSUE THREAD

**Issue by afc163** [leejaen/react-lz-editor#10]

**Comment by leejaen** [comment]
因为这个编辑器最初开发时antd版本还在1.4左右，加上那时为了方便直接写的当时antd的默认色。后来想过改，但是在npm上的组件是把less文件编译成css的，附加antd的主题后生成的css有15000多行，而且在用户自定义主题后没有应用新主题色，所以一直没有改过来。
现在提交的代码可以显示默认色，但还是没有解决好自定义主题色的问题……
