### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by LitileXueZha** [leejaen/react-lz-editor#101]
额，现在开发用的是最新版本react 16，它已经把属性验证prop-types单独抽离出来，所以嵌入时运行出错了，该怎么办啊

**Comment by LitileXueZha** [comment]
![image](https://user-images.githubusercontent.com/22041474/33049746-6c82824e-ce9c-11e7-9c28-9fabc423f139.png)

**Comment by leejaen** [comment]
嗯嗯，看来我应该去掉propTypes的方式，感谢反馈

**Comment by leejaen** [comment]
新版0.11.7已经去掉了propTypes，谢谢，祝好运
