### ISSUE TITLE
上传图片返回成功,点击弹窗确定报错

### ISSUE THREAD

**Issue by huangjiangit** [leejaen/react-lz-editor#109]
先感谢楼主贡献的组件;

上传图片的配置我是根据你的test文件

const uploadProps = {
      action: "https://mysevice/upload",
      onChange: this.onChange,
      listType: 'picture',
      fileList: this.state.responseList,
      data: {...},//这里是我自定义的参数
      multiple: true,
      //beforeUpload: this.beforeUpload,
      showUploadList: true
    }

![image](https://user-images.githubusercontent.com/18650947/33653231-5b36af12-daa7-11e7-9b84-44bb447d367a.png)

就是我点击上传图片之后,返回成功了,点击确定之后报上面的错误 , 还望楼主回复,不胜感激

**Comment by morningbzy** [comment]
看上去是上传图片跨域了，尝试一下把图片服务器  https://myservice/upload 支持跨域访问？

**Comment by huangjiangit** [comment]
应该不是跨域的问题吧；

你看我的操作步骤：
1：点击上传，选择图片,然后就报错如下，test打印是我服务器返回的，证明上传成功了，而且我查看图片链接地址  是能看到图片的
![image](https://user-images.githubusercontent.com/18650947/33711570-76188034-db7f-11e7-947d-4254f1be0155.png)
![image](https://user-images.githubusercontent.com/18650947/33711602-8a3fe890-db7f-11e7-9f10-c548ff4d14d4.png)

2：然后点击弹窗确认键，报错如下
![image](https://user-images.githubusercontent.com/18650947/33711635-a7797516-db7f-11e7-9eca-368853604b60.png)

下面是我onChange方法

![image](https://user-images.githubusercontent.com/18650947/33711707-dc7b5a5e-db7f-11e7-836e-a21eb2a95294.png)

**Comment by Lumend** [comment]
同样遇到这个问题

**Comment by leejaen** [comment]
应该是您返回的图片列表对象没有对应的属性名url，返回的图片列表格式：
```
[{...,url:'http://xxx',...},{...,url:'http://yyy',...},...]
```
你看是不是这个格式？
或者，你在node包里publish\editor\toolBar\mediaImageUploader.js第的successLoading方法中添加一行log，看是否有这个url属性：
```
    console.log('this.state.images',this.state.images);
```

**Comment by huangjiangit** [comment]
好像是我返回的格式对  
file.url = file.response.files[0].url;应该加个这行

但是我这里图片格式不对 ,是不是被什么覆盖了
![image](https://user-images.githubusercontent.com/18650947/33814775-975a58f4-de67-11e7-88c3-cfa7436c48c7.png)
这个图片样式不和谐，楼主这里好像又没有自定义上传图片大小
