### ISSUE TITLE
基于react-create-app+antd安装之后报错

### ISSUE THREAD

**Issue by buxuku** [leejaen/react-lz-editor#11]
`Error in ./~/react-lz-editor/editor/toolBar/colorControls.js
Module not found: [CaseSensitivePathsPlugin] `C:\Users\buxuku\Documents\work\project\ant-test\node_modules\react-lz-editor\editor\toolBar\ColorButton.js` does not match the corresponding path on disk `colorButton.js`.

 @ ./~/react-lz-editor/editor/toolBar/colorControls.js 9:19-43

Error in ./~/react-lz-editor/global/supports/methods/public.js
Module not found: 'datas/url.jsx' in C:\Users\buxuku\Documents\work\project\ant-test\node_modules\react-lz-editor\global\supports\methods

 @ ./~/react-lz-editor/global/supports/methods/public.js 5:11-35`

**Comment by leejaen** [comment]
这个问题是由于不同操作系统区分文件名大小写特性导致，最新版本已经修复，程序员果然万不可用windows开发。

**Comment by buxuku** [comment]
`Error in ./~/react-lz-editor/editor/utils/stateUtils/styleToCSS.js
Module not found: 'react/lib/CSSProperty' in C:\Users\buxuku\Documents\work\project\ant-test\node_modules\react-lz-editor\editor\utils\stateUtils

 @ ./~/react-lz-editor/editor/utils/stateUtils/styleToCSS.js 7:19-51`

更新之后，还有一处错误提示

**Comment by leejaen** [comment]
能否提供一下你使用的 react 版本是多少？

**Comment by buxuku** [comment]
`"dependencies": {
    "antd": "^2.7.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-lz-editor": "^0.9.18",
    "react-router": "^3.0.2"
  }`

**Comment by leejaen** [comment]
因为react在版本15.4之后移动文件react/lib/CSSProperty到react-dom/lib/CSSProperty 导致此问题，现已修复。
