### ISSUE TITLE
编辑回填图片问题

### ISSUE THREAD

**Issue by LeeHarlan** [leejaen/react-lz-editor#12]
插入图片时img标签外会包一层figure标签，但在回填时figure内的图片不能正常显示，有没有一个解决办法。

**Comment by leejaen** [comment]
请重新安装最新版本 0.9.27 查看。

**Comment by LeeHarlan** [comment]
这样显示是没问题了，但是编辑内容的时候图片删除的体验又不好了！！！我最后把转换换成convertToRaw，convertFromRaw...之后一切都正常了

**Comment by leejaen** [comment]
给个pr？

**Comment by LeeHarlan** [comment]
已PR，[AtomicBlockUtils is not parsing images after loading editor content from database](https://github.com/facebook/draft-js/issues/309)因为这个所以另外添加原生格式支持。

**Comment by leejaen** [comment]
已pull，当时在做图片支持功能时，遇到这个问题，这个方式会使用户最后拿到的数据只支持draftjs编辑器，所以自己添加了 “convertHtmlToState” 和 “convertStateToHtml” 的功能，可以导出HTML，但没有解决编辑器中图片删除、选中的痛点。导出Raw保存不失一个好思路。 👍
