### ISSUE TITLE
请教下：用dva，使用这个，第一次npm run build:dll 报错怎么处理呢

### ISSUE THREAD

**Issue by laiyiyi** [leejaen/react-lz-editor#137]
用dva，使用这个，第一次npm run build:dll 报错怎么处理呢
![image](https://user-images.githubusercontent.com/12541388/38008739-e4649e92-3282-11e8-8299-88e3cbc4091a.png)

**Comment by leejaen** [comment]
需要添加对应的file-loader，因为这里面用了icon-font
