### ISSUE TITLE
cbReceiver 调用setState 光标会乱跑

### ISSUE THREAD

**Issue by mrmeisen** [leejaen/react-lz-editor#146]
cbReceiver 调用setState 光标会乱跑
望解决

**Comment by suncunhu** [comment]
试试在组件里 添加 
 `    shouldComponentUpdate() {
        return false;
    }`

**Comment by jyear** [comment]
这是一个很大的坑 讲真

**Comment by jyear** [comment]
组件内部该处理这个问题 如果外部改变传入的数据和内部一样  
编辑器内部就不做任何操作  我估计他重新赋值并且清空了本身的
没时间去看源码

**Comment by hnsylitao** [comment]
#145 可以参考我最后的解决方案
