### ISSUE TITLE
看起来挺不错的，能不能增加一个html源码编辑功能

### ISSUE THREAD

**Issue by jianghejie** [leejaen/react-lz-editor#15]
能不能增加一个html源码编辑功能，有时后遇到极端的情况会用到

**Comment by leejaen** [comment]
HTML代码编辑暂时先不加了，现在还没有做到支持所有标签属性，markdown应是可以的，感谢建议

**Comment by leejaen** [comment]
已实现markdown编辑，请参考前一条的引用评论
