### ISSUE TITLE
react-lz-editor能否提供一个图片连接功能

### ISSUE THREAD

**Issue by Liuqing650** [leejaen/react-lz-editor#19]
## 建议在图片上传功能中增加一个连接显示图片的功能
react-lz-editor的界面看起来非常舒服，图片上传的功能目前只支持七牛是吗?能否再增加一个功能，图片和视频加入一个超链接选择框，像下面这样的：
![image](http://img.mabylove.cn/question/edit-image.gif)

#### 如果上面预览图片无效，请点击下面的连接
[示例路径](http://img.mabylove.cn/question/edit-image.gif) 

```
// 就像这样简单的操作方式
const url = 'http://img.mabylove.cn/question/edit-image.gif';
return <img src={url } />
```

多增加一个选项或则配置项，可以选择多种方式呈现内容，这样或许使用起来同样非常的方便。

**Comment by leejaen** [comment]
👍 正有此意，但现在图片操作上有个体验不是很好，所以一直没动，过几日应该可以实现

**Comment by leejaen** [comment]
0.10.13版本已提供
