### ISSUE TITLE
npm run test 之后报错

### ISSUE THREAD

**Issue by weishijun14** [leejaen/react-lz-editor#2]
$ npm run test

> react-lz-editor@1.0.0 test D:\react-lz-editor-master
> echo "Error: no test specified" && exit 1

"Error: no test specified"

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\node.exe" "C:\\Users\\Administrator\\App                           Data\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! react-lz-editor@1.0.0 test: `echo "Error: no test specified" && exit 1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-lz-editor@1.0.0 test script 'echo "Error: no test s                           pecified" && exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-lz-editor packa                           ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo "Error: no test specified" && exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-lz-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-lz-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\react-lz-editor-master\npm-debug.log

**Comment by leejaen** [comment]
抱歉，暂时还没有实现测试脚本，您可以 clone 代码后，依次执行 
npm install
npm run dev
查看运行效果。
