### ISSUE TITLE
请问如何把内容转为html

### ISSUE THREAD

**Issue by whevether** [leejaen/react-lz-editor#20]
我编辑之后把内容存在数据库中，数据库看是html.但是输出数据的时候是纯文本格式。如何把内容转为html格式?

**Comment by leejaen** [comment]
编辑之后，存数据库之前，用的数据不是输出的html了吗？“但是输出数据的时候”这里说的输出是怎么输出？

**Comment by whevether** [comment]
就是把数据取出来,显示到页面上显示是 类似 <h1>Hello</h1> 这样的文本信息;    除非我<div dangerouslySetInnerHTML=={{__html：content}} </div>   但是这样容易被xss攻击.  有没有好点的方法可以不显示文本而是显示html到页面上.

**Comment by leejaen** [comment]
页面上显示HTML内容，在react中只能使用dangerouslySetInnerHTML方式，这个方法等同于设置dom的innerHTML属性，正常的。
