### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by luwenjiechn** [leejaen/react-lz-editor#21]
版本：0.10.12
报错内容：
```
Error in ./~/react-lz-editor/editor/utils/index.js
Module not found: [CaseSensitivePathsPlugin] `E:\Projects\jzez-admin\node_modules\react-lz-editor\editor\utils\stateToMD\main.js` does not match the corresponding path on disk `statetoMD`.

 @ ./~/react-lz-editor/editor/utils/index.js 43:13-40
```

原因不知道。。。我就单纯照着demo写的，在antd中引入了这个编辑器，但是无法通过编译

**Comment by 0xbug** [comment]
[src/editor/utils/statetoMD ](https://github.com/leejaen/react-lz-editor/tree/master/src/editor/utils/statetoMD )这个目录应该是大写命名 `stateToMD`

**Comment by leejaen** [comment]
已经修复，Windows里开发没注意大小写匹配，多谢二位指正，@0xbug @luwenjiechn

**Comment by ouxu** [comment]
Bug+1 啊 并没有解决，下面一行还是小写的，记得改一下~

**Comment by leejaen** [comment]
忽略了发布版，请试试 0.10.19

**Comment by ouxu** [comment]
谢谢~
