### ISSUE TITLE
垂直滚动条回弹

### ISSUE THREAD

**Issue by tanqingyun** [leejaen/react-lz-editor#22]
![image](https://cloud.githubusercontent.com/assets/18432354/24942231/3cfd7bc4-1f82-11e7-938f-9ae7ffc63e42.png)

滚动条滚动到底部后就会回弹到这个位置，照着demo写的。
在编辑器一定高度时触发。
大概在1080左右，超过1200后没有回弹。

**Comment by leejaen** [comment]
这个我注意到了，因为antd的affix组件引起，没有确定具体哪里引起的问题，近期修复。

**Comment by leejaen** [comment]
你的页面再加个br元素更新下pageHeight，看是否仍然有这个问题？
