### ISSUE TITLE
为什么toolbar里面就是居中 居左不能用，点了样式改了  但是内容里面没变

### ISSUE THREAD

**Issue by yiranlee** [leejaen/react-lz-editor#23]
点了居中  内容没有居中 ，但是实际内容加了center的样式

**Comment by leejaen** [comment]
是不是markdown模式？

**Comment by yiranlee** [comment]
html 格式 在你的demo页面 是可以的   转到我的页面下 就不行  但是通过receivehtml 打印出的  又是对的

**Comment by leejaen** [comment]
用浏览器开发者工具看看是不是样式被你自己定义的覆盖了？
