### ISSUE TITLE
请教下大神，如何自定义上传图片方法呢？

### ISSUE THREAD

**Issue by lpp288** [leejaen/react-lz-editor#28]
LzEditor配置的地方只有uploadConfig，我不想走七牛上传，在哪自定义一个上传方法呢

**Comment by buxuku** [comment]
我也希望能够配置成自己的上传接口，上传到自有服务器上面。目前作者还没有提供支持，希望作者能够早日实现吧。

**Comment by buxuku** [comment]
目前react-draft-wysiwyg和antd的图片上传都是使用的配置接口的形式，希望作者能够也实现这样的效果。

**Comment by leejaen** [comment]
这个功能属于硬需求，会提供的，但最近几天即将忙疯，可能还要过个十几天……

**Comment by shihuojian** [comment]
希望可以怎讲代码编辑

**Comment by shihuojian** [comment]
希望可以增加代码编辑，看好

**Comment by jaguaryouth** [comment]
好的，支持作者，等待自定义上传~

**Comment by yangguixue** [comment]
自定义上传有没有搞定呢 @leejaen

**Comment by leejaen** [comment]
@yangguixue ,抱歉了，我还没时间实现呢……

**Comment by leejaen** [comment]
@yangguixue 可能还要过几天时间才行

**Comment by HengCC** [comment]
图片上传还是没搞定吗? 估计就因为这个没法用了. 只要支持自定义URL. 返回一个文件上传后的访问地址就可以了. 不过要注意文件上传有的服务器需要授权. 要考虑支持在header中增加授权.

**Comment by buxuku** [comment]
我也一直在等图片自定义上传功能来部署到生产环境了。希望作者能够继续保持更新。

**Comment by luocong2016** [comment]
自定义上传配置啊
facebook/Draft 确实不错支持

**Comment by HengCC** [comment]
@luocong2016  确实, 最近打算基于draftjs来重新定制一套. 实现起来应该不难.

**Comment by fuyi-zhou** [comment]
请问一下自定义上传图片的功能还没做吗？？

**Comment by shangsinian** [comment]
能不能先支持一下插入图片标签的形式呢？

**Comment by hanbeib** [comment]
我是用七牛上传，也会报错，好像用不了

**Comment by vimplus** [comment]
啥时候能支持？我也等着上生产，就因为这个图片上传不能支持自己服务器的原因估计很多人放弃了

**Comment by shihuojian** [comment]
我是早放弃这个了……

发自我的 iPhone

**Comment by leejaen** [comment]
已提供此功能支持，请参考uploadProps属性、[Antd.Upload](https://ant.design/components/upload-cn/)
