### ISSUE TITLE
与 antd 自定义 theme 样式冲突

### ISSUE THREAD

**Issue by Evilcome** [leejaen/react-lz-editor#29]
如果项目中使用 react-lz-editor，再按照 antd 的[自定义样式](https://ant.design/docs/react/customize-theme-cn)去配置，由于下面的代码：
```
import 'antd/dist/antd.css';
```
导致样式被覆盖，建议使用推荐的 babel-plugin-import 方式的样式文件导入。
```
["import", { "libraryName": "antd", "style": true }]
```

**Comment by Evilcome** [comment]
@leejaen  本来想做个PR，发现你似乎还有一部分自定义样式。我想大多数情况大家都是同时使用 antd 和 react-lz-editor，所以是否应该优先继承用户已经定义好的 antd 样式呢？

**Comment by leejaen** [comment]
这属于我发布问题，调试后忘记去掉样式，正常是没有手动导入css的，又发布了新版本解决，多谢反馈。
