### ISSUE TITLE
Add Live demo

### ISSUE THREAD

**Issue by afc163** [leejaen/react-lz-editor#3]

**Comment by leejaen** [comment]
\(^o^)/~  哈哈，偏右大神造访受宠若惊……
Demo is here: https://leejaen.github.io/ 
因为上传图片视频多媒体等文件需要后端服务器接口配合，这部分暂时没有实现在线demo接口，所以暂时通过配置去掉了。

**Comment by afc163** [comment]
加到项目描述和 README 中吧，不然找不到。

**Comment by leejaen** [comment]
多谢偏右指导，现在已经加上链接，这个是我疏忽考虑不周。再次致谢。
