### ISSUE TITLE
引入editor后就报异常

### ISSUE THREAD

**Issue by zfeidy** [leejaen/react-lz-editor#31]
异常如下：
`
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/less-loader?sourceMap!./~/antd/lib/checkbox/style/index.css
Module build failed: media definitions require block statements after any features
 @ /Users/Xixi/Test/node_modules/antd/lib/checkbox/style/index.css (line 133, column 7)
 near lines:
   }
   @media \0screen {
     .ant-checkbox-checked .ant-checkbox-inner:before,
 @ ./~/antd/lib/checkbox/style/index.css 4:14-159
`

环境：
"node": "6.3.1"
"react": "^15.5.4"
"react-dom": "^15.5.4"
"antd": "^2.10.0"

webpack的配置如下：
`
 {
                test: /\.(less|css)$/,
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap!postcss!less?sourceMap')
}, {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: "url-loader?limit=10000&mimetype=application/font-woff"
}, {
                test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: "file-loader"
}

`

**Comment by leejaen** [comment]
多次尝试新版本无此问题，现在解决了？

**Comment by vimplus** [comment]
我也会报这种错，要装一个file-loader，不过我第一次安装的时候不需要装file-loader不知道为啥
