### ISSUE TITLE
button样式对 全局 antd 样式是侵入的.

### ISSUE THREAD

**Issue by uinz** [leejaen/react-lz-editor#36]
对 antd 的默认样式已经做了修改比如 `<Button />` 组件的 `border-color` 改为了红色.

引入 `react-lz-editor` 后会对全局的 `.ant-btn:hover, .ant-btn:focus` 进行覆盖.

**Comment by leejaen** [comment]
您用的那个版本？0.10.16应该是没问题的

**Comment by uinz** [comment]
就是 0.10.16
我觉得应该是继承antd 的样式 不应该引入 css

**Comment by leejaen** [comment]
您能定位到那一处css影响到全局的button了吗？或者是提供一下抓图参考？编辑器组件里面重写的button css只限制了编辑器里面，所以需要尽量全的信息来确认。

**Comment by leejaen** [comment]
之前的版本确实会存在加载不了自定义样式的问题，确定不是旧版本缓存的问题？

**Comment by uinz** [comment]
我先close, 确认问题后再打开吧

**Comment by cliberal** [comment]
![image](https://user-images.githubusercontent.com/19610094/28248111-59d91bba-6a71-11e7-8fad-7ce4a9d5cfc7.png)
