### ISSUE TITLE
虚心求教一个问题

### ISSUE THREAD

**Issue by czy0729** [leejaen/react-lz-editor#38]
虽然没用上大佬的编辑器，但是也参考了一下大佬的代码。
小弟现在有一个问题，多方搜查也解决不了。

http://wx3.sinaimg.cn/mw690/715ed77dgy1fgv5vfbrbwg20a70hz7oi.gif
这图是通过decorator把特定字符串转成图片。但是这样图片退格总是删不掉，而且总在最后。

http://wx3.sinaimg.cn/mw690/715ed77dgy1fgv5veqiaeg20a70hzwvk.gif
这图是未替换的字符，但是也是跑了一次decorator的，但是这个却没什么问题。

大佬能不能提供一下思路，小弟不胜感激

**Comment by czy0729** [comment]
居然被我蒙对了，太坑了，搞定啦，而且我发现大佬你居然也向官方问过这个问题，而且没人鸟你:-D

**Comment by leejaen** [comment]
你是如何搞定这个问题的，能否共享一下思路或方法？我这里用的替换字符是“~”但是为了显示效果偏移到容器之外，试过很多方法都不完美。

**Comment by czy0729** [comment]
draft这个图片一块删掉，其实是根据里面的字体长度去算的，假如里面没有文字，总是有问题的。
现在我可能也是你这个办法，把图片放在容器的背景里面，但是保留了字体，使字体颜色透明，并且使用了一些很不好的css去令这个文字尽可能不被鼠标点击到。
不过我这个是emoji，手机里面使用还算过得去。

**Comment by czy0729** [comment]
现在其实还有小地方体验很不好，你这个demo我看见的效果也是一样。
就是这两个图片之间总存在一行，手机里面看2个图片之间有一段空隙特别难看，但是这一行退格又会把上面的图片删掉，相当难搞

**Comment by leejaen** [comment]
是的，这些问题的确存在，并且没有找到最好的解决方法，原因是draftjs没有提供对图片的全面曹组，现在这些方法应该属于hack的，感谢。
