### ISSUE TITLE
[建议]html格式下，增加“关闭html过滤”配置项

### ISSUE THREAD

**Issue by keepnode** [leejaen/react-lz-editor#43]
在编辑一些比较特殊的内容，如编辑一个网页模板，确实需要导入js和css文件，这个功能建议，在html源代码编辑中实现。具体参考例子：[查看](http://kindeditor.net/ke4/examples/filter-mode.html)

**Comment by leejaen** [comment]
draft.js支持的格式不是很全面，所以没有加这个功能，也许以后draft会有不错的支持，不过看draft.js 的更新力度好像他们不这么想

**Comment by keepnode** [comment]
thanks! :)
