### ISSUE TITLE
您好，引入之后，放入项目中，启动后报错，

### ISSUE THREAD

**Issue by xukaifengit** [leejaen/react-lz-editor#44]
报下面的错，是因为什么？
 @ ./~/antd/lib/modal/style/css.js 5:0-22
 @ ./~/react-lz-editor/editor/index.js
 @ ./~/react-lz-editor/index.js
 @ ./jsx/pages/home.js
 @ ./jsx/router.js
 @ ./jsx/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8989 webpack/hot/dev-serve
r ./jsx/app.js

ERROR in ./~/antd/lib/message/style/index.css
Module parse failed: D:\项目\react-demo\node_modules\antd\lib\message\style\inde
x.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .ant-message {
|   font-size: 12px;
|   position: fixed;
 @ ./~/antd/lib/message/style/css.js 5:0-22
 @ ./~/react-lz-editor/editor/index.js
 @ ./~/react-lz-editor/index.js
 @ ./jsx/pages/home.js
 @ ./jsx/router.js
 @ ./jsx/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8989 webpack/hot/dev-serve
r ./jsx/app.js

**Comment by leejaen** [comment]
这个……我也没看出来呀，问题修复了吗？

**Comment by leejaen** [comment]
refs to #34
