### ISSUE TITLE
引入这个插件后会编译整体会再加入一遍CSS样式

### ISSUE THREAD

**Issue by smallchicken** [leejaen/react-lz-editor#46]
引用了这个插件后，编译后index.css文件里又加入了大量的antd的css和初始化的CSS,导致以前的样式和antd的组件样式全部错乱，请问如何取消掉组件里的样式引入呢？
![image](https://user-images.githubusercontent.com/21360019/27982192-95f9eb1e-63ce-11e7-9676-88596f2b85d9.png)

**Comment by leejaen** [comment]
试着把antd的样式在最后导入，这样就会用后面的覆盖前面的。
之前版本有过这个问题，最新的应该没有啦，你的版本是最新的吗？

**Comment by jaryway** [comment]
我也发现了这个问题。
因为需要使用router,同时使用了[code-splitting](https://reacttraining.com/react-router/web/guides/code-splitting)导致样式无法提取到单独的样式文件中，因此我在入口文件把antd的样式引入了，
```js
import './assets/antd/dist/antd.min.css'
```
这样成功的把antd的样式提取到了单独的样式文件中。
然而，打包后发现文件很大，通过webpack-bundle-analyzer分析发现react-lz-editor又重新引了一遍antd的样式，而且是嵌入js文件中。

![20170815153038](https://user-images.githubusercontent.com/5987056/29306137-9ff62290-81ce-11e7-9d68-cf26096790b2.jpg)

![20170815152842](https://user-images.githubusercontent.com/5987056/29306108-77eabfcc-81ce-11e7-840f-686de6665fd8.jpg)

**Comment by lianliu** [comment]
clone 代码在本地做css 自定义后也出现这个问题（v.1.0.2）。

```
yarn run publish
```

后指向了／publish／index.js
