### ISSUE TITLE
运行中报 Error: Cannot find module "datas/base" ，如何解决

### ISSUE THREAD

**Issue by maccyluo** [leejaen/react-lz-editor#5]
Error: Cannot find module "datas/base"

webpackMissingModule — publicDatas.js:16Error: Cannot find module "datas/base"

**Comment by leejaen** [comment]
这个错误是我疏忽webpack打包发布造成的，现在最新版本已经修复，多谢反馈！^_^

**Comment by maccyluo** [comment]
npm install react-lz-editor --save 更新版本时报下面错误

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-lz-editor" "--save"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: js-base64@^0.2.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.2, 2.1.1, 2.1.0, 2.0.7, 2.0.6
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'react-lz-editor'
npm ERR! notarget
