### ISSUE TITLE
上传图片无法点击确定

### ISSUE THREAD

**Issue by buxuku** [leejaen/react-lz-editor#51]
![qq 20170721113829](https://user-images.githubusercontent.com/7866330/28448276-3eecdf30-6e09-11e7-8262-b6699b20765b.jpg)

请问是否在上传成功之后需要返回特定的图片地址格式？

**Comment by ykx456654** [comment]
同问，是不是要在uploadProps里配置地址？

**Comment by leejaen** [comment]
不是的，这个我需要再完善一下

**Comment by vimplus** [comment]
上传只调用了一次onChange，请问怎么回事？

**Comment by leejaen** [comment]
0.12.21已发布，上传已本地测试通过

**Comment by suncunhu** [comment]
这尼玛是坑爹啊, npm官网上最新的还是0.12.1版本,
都大半年过去了，还没发布吗?

**Comment by suncunhu** [comment]
版本号 不应该是和package.json的version 相同吗?

https://github.com/leejaen/react-lz-editor/issues/58
