### ISSUE TITLE
图片上传成功后，在编辑器里正常显示，但是传入到receiveHtml里的图片路径不对

### ISSUE THREAD

**Issue by deepred5** [leejaen/react-lz-editor#59]
使用编辑器遇到了如下几个问题：
1. 图片上传成功后，实际传入到receiveHtml中的图片路径被截断了，导致下一次编辑文章，图片不能正常显示
2. 第一次点击上传图片，成功上传后，下一次点击上传图片，之前上传的图片仍然在列表中，导致几秒之后自动弹出Modal。是否可以在每次上传完图片，点击确认后，自动清空fileList

**Comment by buxuku** [comment]
第2点同样的需求，希望上传完成之后，点确定就清空上传列表，否则第二次无法再上传了。

**Comment by deepred5** [comment]
在编辑器中，图片是正常显示的，地址正确：
```
<img src="/images/20170731/img-113440hgF0Wq.jpg?t=foreditor" class="media">
```
但是在receiveHtml中显示的图片地址是
```
<p><img src="/images/20170731/img"/></p>
```
可以看到，图片地址被截断了

**Comment by XindaSayHi** [comment]
同样遇到了图片路径被截断的问题，经过测试发现如果在图片路径中出现中划线 `-` ，就会出现此问题，保证图片路径中不出现`-`就能够正常使用，可以调整目录和文件命名来暂时规避这个问题。

**Comment by zerozrn** [comment]
图片上传成功,为什么自动出现图片预览?这样无法选择别的图片

**Comment by HelloSkull** [comment]
为什么出现 - 就会被截断呢？能不要修改地址么？有些图片服务器的地址就是有 - 的
