### ISSUE TITLE
Example 中注释“上传地址，现在暂只支持七牛上传”，如果希望做到上传到自有服务器上，服务端需要实现哪些接口，是否有指导文档？多谢支持！

### ISSUE THREAD

**Issue by maccyluo** [leejaen/react-lz-editor#6]
Example 中注释“上传地址，现在暂只支持七牛上传”，如果希望做到上传到自有服务器上，服务端需要实现哪些接口，是否有指导文档？多谢支持！

参考：

QINIU_URL: "http://up.qiniu.com", //上传地址，现在暂只支持七牛上传

const uploadConfig = {
        QINIU_URL: "http://up.qiniu.com", //上传地址，现在暂只支持七牛上传
        QINIU_IMG_TOKEN_URL: "http://www.yourServerAddress.com/getQiniuUptoken.do", //请求图片的token
        QINIU_PFOP: {
          url: "http://www.yourServerAddress.com/QiniuPicPersist.do" //七牛持久保存请求地址
        },
        QINIU_VIDEO_TOKEN_URL: "http://www.yourServerAddress.com/getQiniuUptoken.do", //请求媒体资源的token
        QINIU_FILE_TOKEN_URL: "http://www.yourServerAddress.com/getQiniuUptoken.do?name=patch", //其他资源的token的获取
        QINIU_IMG_DOMAIN_URL: "https://image.yourServerAddress.mobi", //图片文件地址的前缀
        QINIU_DOMAIN_VIDEO_URL: "https://video.yourServerAddress.mobi", //视频文件地址的前缀
        QINIU_DOMAIN_FILE_URL: "https://static.yourServerAddress.com/", //其他文件地址前缀
      }

**Comment by leejaen** [comment]
这个功能现在还没有做出兼容，不过今后会支持的，服务端代码稍等几天会放出示例，最近有点点忙。

**Comment by maccyluo** [comment]
你好，这个功能 两周内能否放出来呢？我们产品上线前希望能够替换掉服务器地址，多谢支持啊，辛苦啦！

**Comment by leejaen** [comment]
我在这个月15日后才能有比较充裕的时间，所以可能完成不了这项工作，不过我尽量放出java版本的七牛接口示例，应该会对你有些帮助。多谢反馈。
