### ISSUE TITLE
您好，点击上传按钮会报一个语言包相关的错误

### ISSUE THREAD

**Issue by HansPeng** [leejaen/react-lz-editor#62]
![image](https://user-images.githubusercontent.com/15026813/29206798-1960c7c8-7eb6-11e7-89b9-5d19da8726ea.png)
![image](https://user-images.githubusercontent.com/15026813/29206775-fd76cabc-7eb5-11e7-9707-2fd7fe707ef7.png)
![image](https://user-images.githubusercontent.com/15026813/29206788-0f9e2438-7eb6-11e7-979e-d46118d053d8.png)
如图所示，貌似是取不到语言设置的问题，请问怎么解决？

**Comment by jdongdong** [comment]
我也遇到同样的问题

**Comment by leejaen** [comment]
两位用的什么浏览器？

**Comment by jdongdong** [comment]
chrome浏览器
版本：59.0.3071.115

**Comment by leejaen** [comment]
0.11.1 已经解决
