### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by HansPeng** [leejaen/react-lz-editor#63]
您好，关于图片上传，有两个问题想请教一下：
1. 图片上传模态框有一句提示‘您可以上传 10 个类型为 image/jpeg, image/png, image/jpg, image/gif, image/webp 的文件。’， 但是每次上传一张图片后就自动跳到图片预览模态框了，没办法上传10个啊，请问这句话可以改为自定义的吗？
![image](https://user-images.githubusercontent.com/15026813/29450979-7555896a-8433-11e7-86de-7514eceb81de.png)
2. 我这边每次上传成功后都会报一个错，请问是什么原因？
![image](https://user-images.githubusercontent.com/15026813/29451064-d23504da-8433-11e7-9f1d-f7cd367ddd4f.png)

我的react-lz-editor是0.11.1版本的。

**Comment by leejaen** [comment]
这个提示也许我得去掉，这是以前业务特性，没必要都需要，我会去掉的。
只上传一个图片的问题，在配置uploadProps时有没有配置antd.upload的multiple: true？这个属性表示是否支持多选上传

**Comment by HansPeng** [comment]
@leejaen 我没有设置multiple: true，因为我这边的需求就是单张上传，所以你那个可上传10个的提示对用户会有点误导作用，希望能修改一下。关于那个报错，我检查了一下，是在上传完图片生成预览的模态框报的，应该是react-lz-editor/src/editor/toolBar/mediaImageUploader.jsx里的这段代码你遍历了一个数组，但是渲染出来的div并没有传key属性，所以报错了 https://fb.me/react-warning-keys。

![image](https://user-images.githubusercontent.com/15026813/29505812-01439d88-867b-11e7-9dd9-0981c8d08d4b.png)

还有个问题，图片预览模态框有个刷新的图标，好像没什么用？而且也没有样式..放那感觉有点奇怪
![image](https://user-images.githubusercontent.com/15026813/29506000-00aacd96-867c-11e7-934f-88616e8dc184.png)

**Comment by XindaSayHi** [comment]
我在上传图图片的时候，上传第一张图片正常，当再次打开上传图片窗口时，会自动跳转到预览界面，这样点击确定会在编辑器中再次添加第一张图片，请问这是什么原因？

**Comment by HelloSkull** [comment]
和楼上的几位遇到了同样的问题，能不能在关掉模态框的时候给个自定义函数啊@leejaen
