### ISSUE TITLE
一开始我是有很多问题想问的，现在我只想说   别！用！

### ISSUE THREAD

**Issue by yiluzhang** [leejaen/react-lz-editor#65]
清空内容后会报
`Invalid DraftEditorContents structure.`
`Got unexpected null or undefined.`

图片上传完会出现警告
`Each child in an array or iterator should have a unique "key" prop. Check the render method of `ImgStyleControls`.
还会有错误
`The prop `fileList[0].url` is marked as required in `UploadImage`, but its value is `undefined`.`

上传完自动进入图片预览，关闭再打开一样，无法继续上传。

根本无法插入图片链接，地址校验永远无效。

为什么上传完成图片链接后面加了`?t=foreditor`?

为什么插入视频里面有上传过的图片？点击确定居然插入了图片地址的视频？而且插入的数量相当惊人！

**Comment by leejaen** [comment]
谢谢反馈，这些我会慢慢改掉，只是现在我的业余时间不太丰富，对不起让朋友失望了。。。

**Comment by ipconfiger** [comment]
demo都在报一堆错, 真是不敢用, 浪费了3天的时间来折腾. 现在对编辑器的要求就3点:
1. 配置简便
2.稳定不报错
3.输出html整洁

搞一堆花哨功能其实并不一定讨巧, 比如这个里头的图片上传

**Comment by leejaen** [comment]
@ipconfiger 所有项目都可以配置去掉，不需要的图片上传可以配置image={false}

**Comment by ipconfiger** [comment]
但是需要图片上传的嘛, 克服万难终于可以传上去了, 结果onChange后就报错了, 图片地址也没法插入到editor里, 很郁闷的撒

**Comment by leejaen** [comment]
onChange后的报错检查一下实现的函数，这个完全代理给antd的upload了，是不是写的有错误？

**Comment by ipconfiger** [comment]
我再onChange里啥都没干, 报错的是  mediaImageUploader.js  这个文件. 191行
我的版本是 npm 上的.
我加了个日志后发现, this.state.images 一直都是[] , 但是在上传完成后就成了undefind了, 不晓得是那里改的

**Comment by leejaen** [comment]
@ipconfiger 我稍后看一下。。。

**Comment by ipconfiger** [comment]
要是现在的version不存在这个问题, 能否先更新一下npm上的版本?

**Comment by ipconfiger** [comment]
感觉问题都是在图片上传这里, 话说能不能不要做这么复杂啊, 老老实实上传完一张图片就直接插入内容不好么?

**Comment by ipconfiger** [comment]
@leejaen  请问有解么?

**Comment by leejaen** [comment]
@ipconfiger 可以的，不过我昨天调试没发现问题，可能需要跟你一起看一下
