### ISSUE TITLE
demo也上传图片不能在报错

### ISSUE THREAD

**Issue by ipconfiger** [leejaen/react-lz-editor#68]
![http://wx1.sinaimg.cn/large/578b198bgy1fj1tcmfqfdj21kw0u4dp5.jpg](http://wx1.sinaimg.cn/large/578b198bgy1fj1tcmfqfdj21kw0u4dp5.jpg)

**Comment by leejaen** [comment]
DEMO中存在服务器验证，上传不可用

**Comment by ipconfiger** [comment]
但是, 在console里有很明确的报错啊, 点确定也什么都没有发生

**Comment by leejaen** [comment]
DEMO 用的又拍云，有服务器验证，所以无法上传。这里的图片上传功能我稍后会去掉，以免误导。。。
