### ISSUE TITLE
富文本编辑器解析图片异常

### ISSUE THREAD

**Issue by Durianicecream** [leejaen/react-lz-editor#70]
### 图片地址:http://ac-hw4qisvm.clouddn.com/f2704e4c92a1018151b0.jpg

![image](https://user-images.githubusercontent.com/16221326/29906883-b22f435a-8e4a-11e7-89c6-1a1deb1a04ca.png)

图片是七牛的图片，解析出来的dom节点是这个，也就是说“-”之后的src都无法被解析

![image](https://user-images.githubusercontent.com/16221326/29906898-cdcba40a-8e4a-11e7-995a-8eebdca08639.png)

**Comment by leejaen** [comment]
最新版版0.11.3已经解决这个问题了

**Comment by Durianicecream** [comment]
已经更新到0.11.3了  但是还是会出现这个问题

**Comment by leejaen** [comment]
……我晚上回去看看

**Comment by HelloSkull** [comment]
我来描述一下这个问题。之前是存的时候不对（就是-后面的字符串被截断了），现在是存的时候存了完整地址，但是渲染的时候还是把-后面的字符串截掉了，请看看！

**Comment by leejaen** [comment]
0.11.4版本已经发布，其他问题明天再看……谢各位支持  :pray:

**Comment by HelloSkull** [comment]
上线支持一波，大大辛苦，明日试试最新版本～
