### ISSUE TITLE
请问如何开启html模式下的源码查看？

### ISSUE THREAD

**Issue by cranehe** [leejaen/react-lz-editor#75]
请问如何开启html模式下的源码查看？还是要自己实现？我看再markdown下是有源码这个tool的

**Comment by leejaen** [comment]
很抱歉，这个我没有提供此功能，因为现在不是所有的HTML标签和Css属性都支持，所以没有提供。不过可以自己实现这个功能。

**Comment by cranehe** [comment]
好的谢谢了
