### ISSUE TITLE
怎么使用？？

### ISSUE THREAD

**Issue by fe719319448** [leejaen/react-lz-editor#89]
1：npm install react-lz-editor --save
2：import LzEditor from 'react-lz-editor';
3： <LzEditor active={true} importContent={this.state.htmlContent} cbReceiver={(content) => this.receiveHtml(content)} />

在使用组件的时候没有任何反应，demo 页可以弄一个单独的吗？

**Comment by huanganqi** [comment]
哎，连个demo都弄不好，真不靠谱
